// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MWF.Projects.Infraestructure.DataContext;

#nullable disable

namespace MWF.Projects.Infraestructure.Migrations
{
    [DbContext(typeof(MWF.ProjectsDbContext))]
    partial class MWF.ProjectsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MWF.Projects.Domain.Entities.MWF.ProjectsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ExampleString")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MWF.Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
